# ___
# [ Geoinformatika ]

## Strojové a hluboké učení


**Katedra aplikované geoinformatiky a kartografie**, Přírodovědecká fakulta, Univerzita Karlova
Albertov 6, 128 43 Praha 2

*Lukáš Brodský lukas.brodsky@natur.cuni.cz*

### Neuronová síť v Numerickém Pythonu 
bez dedikovaných knihoven (PyTorch, TensorFlow, Keras) 

In [18]:
# Knihovny pro praci
import os

import numpy as np
print('Numpy verze: {}'.format(np.__version__))

import pandas as pd 
print('Pandas verze: {}'.format(pd.__version__))

Numpy verze: 1.21.4
Pandas verze: 1.3.4


In [15]:
# Matice
# 4 * 2 
a = np.array([[1, 0], [0, 1], [0, 2], [0, 3]])
# 2 * 3 
b = np.array([[4, 1, 3], [2, 2, 3]])

In [16]:
print(a)
print(b)

[[1 0]
 [0 1]
 [0 2]
 [0 3]]
[[4 1 3]
 [2 2 3]]


In [17]:
# 4 * 3 matice (Dot Product)
c = np.dot(a, b)
print(c)

[[4 1 3]
 [2 2 3]
 [4 4 6]
 [6 6 9]]


In [19]:
os.getcwd()
os.listdir()

'/Users/lukas/Work/prfuk/vyuka/geoinformatika/src/geoinformatika/strojove_hluboke_uceni'

In [76]:
# nacteni mini dat
df = pd.read_csv('test_cls_data.csv')
df.head()

Glucose  BloodPressure  Diabetes
0       86            104         1
1       78            111         0
2       79            114         0
3       77            105         0
4       90            100         1

In [24]:
# 
x = df[['Glucose','BloodPressure']] 
y = df['Diabetes']

In [26]:
# sigmoidni funkce 
def sigmoid(input):
    output = 1 / (1 + np.exp(-input))
    return output

In [27]:
# derivace sigmoidni function
def sigmoid_derivative(input):
    return sigmoid(input) * (1.0 - sigmoid(input))

In [57]:
# trenovani NN 
def train_network(features,label,weights ,bias,learning_rate,epochs):
    for epoch in range(epochs):
        dot_prod = np.dot(features, weights) + bias
        # using sigmoid
        preds = sigmoid(dot_prod) 
        # Vypocet ztrat 
        errors = preds - label 
        # sigmoid deriv. 
        deriva_cost_funct = errors 
        deriva_preds = sigmoid_derivative(preds) 
        deriva_product = deriva_cost_funct * deriva_preds 
        # update the weights 
        weights = weights - np.dot(features.T, deriva_product) * learning_rate
        loss = errors.sum()
        print(loss)
    for i in deriva_product:
        bias = bias - i * learning_rate
    
    return weights, bias  


In [58]:
x.shape

(5, 2)

In [64]:
y.shape

(5,)

In [65]:
y.values.reshape(y.shape[0],1).shape

(5, 1)

In [68]:
np.random.seed(10)
features = x
label = y.values.reshape(y.shape[0],1) 

weights = np.random.rand(2,1) 
bias = np.random.rand(1) 
learning_rate = 0.0004
epochs = 20

In [71]:
weights_final, bias_final = train_network(features, label, weights, bias, learning_rate, epochs)

3.0
3.0
3.0
3.0
3.0
3.0
3.0
2.9999999999999867
2.9999999999990044
2.999999999925474
2.9999999943681033
2.999999570558996
2.9999669873696293
2.9974464551848943
2.817687239179599
0.8439294392698701
0.2898900344277985
0.1623952175091683
0.10040144943879462
0.06321005690835024


In [75]:
# Predikce 
inputs = np.array([[86,104]])
dot_prod = np.dot(inputs, weights_final) + bias_final
preds = sigmoid(dot_prod) >= 1/2
print('Vysledek predikce: {}'.format(preds[0]))

Vysledek predikce: [ True]
